title: "TopoPhotonics Group"
tagline: "At the frontier of topological photonics and laser-crafted devices"
author: mukherjeesebabrata@gmail.com

show_excerpts: false

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

minima:
  date_format: "%b %-d, %Y"

header_pages:
- index.md
- research.md
- publication.md
- talks.md
- groupN.md
- openpositions.md
- contact.md

number_sections: true

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

plugins:
 - jekyll-feed
 - jekyll-seo-tag
